server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/bankdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: changeThisSuperSecretKey1234567890
    accessMillis: 900000
    refreshMillis: 604800000
